#!/usr/bin/env python3
"""Regenerate assets/js/icons.js from the lucide-static package.

Only the icons actually referenced by `data-lucide` in the site's HTML are
inlined, which keeps the bundle small and removes any CDN dependency.

    pip download lucide-static        # not a Python package; use npm instead
    npm pack lucide-static@0.469.0 && tar xzf lucide-static-*.tgz
    tools/build-icons.py package/icons

An icon name that lucide has renamed shows up as a hard error rather than a
silently missing glyph, so the fix is to update the markup.
"""

import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "js", "icons.js")

TEMPLATE = """/* Inline Lucide icons (ISC licensed, from lucide-static %s), limited to
   the set this site uses. Self-hosted so icons never depend on a CDN.
   Generated by tools/build-icons.py; do not edit by hand. */
(function () {
    'use strict';
    var ICONS = %s;

    window.renderIcons = function (root) {
        (root || document).querySelectorAll('[data-lucide]').forEach(function (el) {
            var body = ICONS[el.getAttribute('data-lucide')];
            if (!body) { el.textContent = '\\u2022'; return; }
            var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
            svg.setAttribute('viewBox', '0 0 24 24');
            svg.setAttribute('fill', 'none');
            svg.setAttribute('stroke', 'currentColor');
            svg.setAttribute('stroke-width', '2');
            svg.setAttribute('stroke-linecap', 'round');
            svg.setAttribute('stroke-linejoin', 'round');
            svg.setAttribute('aria-hidden', 'true');
            svg.setAttribute('focusable', 'false');
            svg.innerHTML = body;
            el.replaceChildren(svg);
        });
    };
})();
"""


def used_icon_names():
    out = subprocess.run(
        "grep -roh --exclude-dir=_site 'data-lucide=\"[a-z0-9-]*\"' "
        "--include='*.html' .",
        shell=True, cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    return sorted({m.group(1) for m in re.finditer(r'data-lucide="([a-z0-9-]+)"', out)})


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: build-icons.py <path-to-lucide-static/icons>")
    src, version = sys.argv[1], "0.469.0"

    icons, missing = {}, []
    for name in used_icon_names():
        path = os.path.join(src, name + ".svg")
        if not os.path.exists(path):
            missing.append(name)
            continue
        with open(path, encoding="utf-8") as fh:
            body = re.search(r"<svg[^>]*>(.*)</svg>", fh.read(), re.S).group(1)
        icons[name] = re.sub(r"\s+", " ", body).strip()

    if missing:
        sys.exit("unknown icon names (renamed upstream?): " + ", ".join(missing))

    body = TEMPLATE.replace("%s", version, 1) % json.dumps(
        icons, sort_keys=True, separators=(",", ":")
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(body)
    print(f"wrote {OUT}: {len(icons)} icons, {os.path.getsize(OUT)} bytes")


if __name__ == "__main__":
    main()
